// Extracts visible text from a page's index.html, grouped by <section id="...">,
// and writes the matching Edge Function's corpus.json + corpus.ts.
//
// Usage:
//   node scripts/build-corpus.mjs               → reads ./index.html,        writes supabase/functions/ask/
//   node scripts/build-corpus.mjs --page ai-org → reads ./ai-org/index.html, writes supabase/functions/ask-org/
//
// The output is a JSON array of { section_id, title, text } chunks that
// the Edge Function inlines into its grounding system prompt.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';

// --- Arg parsing: --page <name> ---
// Known pages map to { htmlPath relative to repoRoot, function dir under supabase/functions/ }.
const PAGES = {
  sdlc:   { html: 'index.html',        fn: 'ask' },
  'ai-org': { html: 'ai-org/index.html', fn: 'ask-org' },
};
const args = process.argv.slice(2);
let pageArg = 'sdlc';
for (let i = 0; i < args.length; i++) {
  if (args[i] === '--page' && args[i + 1]) { pageArg = args[i + 1]; i++; }
}
if (!PAGES[pageArg]) {
  console.error(`Unknown --page "${pageArg}". Known: ${Object.keys(PAGES).join(', ')}`);
  process.exit(1);
}

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const page = PAGES[pageArg];
const inputPath = resolve(repoRoot, page.html);
const outputPath = resolve(repoRoot, `supabase/functions/${page.fn}/corpus.json`);
const tsOutputPath = resolve(repoRoot, `supabase/functions/${page.fn}/corpus.ts`);

const html = readFileSync(inputPath, 'utf8');
const dom = new JSDOM(html);
const doc = dom.window.document;

// Strip nodes that aren't reader-visible content.
const STRIP_SELECTORS = [
  'script',
  'style',
  'svg',
  'noscript',
  'template',
  '[aria-hidden="true"]',
  '.podcast-player',
  '#sf-modal-backdrop',
];
for (const sel of STRIP_SELECTORS) {
  for (const el of doc.querySelectorAll(sel)) el.remove();
}

function cleanText(s) {
  return s.replace(/\s+/g, ' ').trim();
}

function firstHeadingText(section) {
  const h = section.querySelector('h1, h2, h3, h4');
  return h ? cleanText(h.textContent) : '';
}

const main = doc.querySelector('main') || doc.body;
// Sections directly under <main>, plus sections one level deep (e.g. inside
// an <div class="article-wrap"> layout wrapper). We skip deeper nesting so
// inner sections get folded into their parent's text rather than double-counted.
const sections = [
  ...main.querySelectorAll(':scope > section, :scope > div > section'),
];

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

const chunks = [];
const usedIds = new Set();
for (const sec of sections) {
  const title = firstHeadingText(sec);
  let id = sec.id || '';
  if (!id) {
    // Derive a stable id from heading, else from class, else from position.
    const classSlug = slugify(sec.className || '');
    id = slugify(title) || classSlug || `section-${chunks.length + 1}`;
  }
  // De-duplicate if two sections slug to the same id.
  let uniqueId = id;
  let n = 2;
  while (usedIds.has(uniqueId)) uniqueId = `${id}-${n++}`;
  usedIds.add(uniqueId);

  const text = cleanText(sec.textContent || '');
  if (!text) continue;
  chunks.push({ section_id: uniqueId, title, text });
}

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, JSON.stringify(chunks, null, 2) + '\n', 'utf8');

// Also emit a TypeScript module so the Edge Function can import it without
// relying on JSON-import flags (keeps the deploy payload a single .ts file).
const tsBody =
  `// AUTO-GENERATED by scripts/build-corpus.mjs — do not edit by hand.\n` +
  `// Regenerate with: npm run build:corpus\n\n` +
  `export type CorpusChunk = { section_id: string; title: string; text: string };\n\n` +
  `export const corpus: CorpusChunk[] = ${JSON.stringify(chunks, null, 2)};\n`;
writeFileSync(tsOutputPath, tsBody, 'utf8');

const totalChars = chunks.reduce((n, c) => n + c.text.length, 0);
console.log(
  `Wrote ${chunks.length} sections, ${totalChars.toLocaleString()} chars → ${outputPath}\n` +
  `                                  → ${tsOutputPath}`
);
